### PR TITLE
Adding dev-container based GH workflow.

### PR DESCRIPTION
**Pull request by sandeepd-nv**

### CODE REVIEW

**Comment by marcinz** [comment]
@trxcllnt's devcontainer: nv-legate/cunumeric#793

**Review by trxcllnt — CHANGES_REQUESTED** [review]
As @marcinz mentions, there's an existing PR to add a devcontainer for cuNumeric and legate.

It already does everything (and more) that's in this one, but @sandeepd-nv let's collaborate on it further if you have additional ideas.

**Comment by sandeepd-nv** [comment]
@trxcllnt sounds good.

**Comment by marcinz** [comment]
@sandeepd-nv Did you close the pull request to create a new one?

**Comment by sandeepd-nv** [comment]
@marcinz yeah sorry about that. I created it before reading Paul's comment.

**Pull request closed without merging**
