### PR TITLE
Enable OpenMP in GH CI.

### PR DESCRIPTION
**Pull request by sandeepd-nv**

### CODE REVIEW

**Review by marcinz — COMMENTED** [review]
Is OpenMP actually used in any tests?

**Comment by sandeepd-nv** [comment]
> Is OpenMP actually used in any tests?

Yes, cunumeric CI has OpenMP tests. We need to build legate.core with OpenMP support for that to work.

**Comment by sandeep-datta** [comment]
> I meant, is OpenMP used in any tests as in this PR? I can see that it is enabled, but is it just for build? I don't see where it is used (the corresponding options).

Yes, it's just for build.

**Review by m3vaz — APPROVED** [review]
+1 Thank You

**Pull request merged**
