### PR TITLE
Allow only one of --legion-dir and --legion-src-dir

### PR DESCRIPTION
**Pull request by jjwilke**

### CODE REVIEW

**Comment by jjwilke** [comment]
Compare with PR #383. Either PR #383 or this PR should get merged.

**Comment by manopapad** [comment]
I think this is the better PR of the two. Can we also add a check in `install.py` that the user shouldn't pass both `legion_dir` (which IIUC has the effect of redirecting the `findpackage(legion)` search to a user-defined directory) and `legion_src_dir`?

**Comment by jjwilke** [comment]
@manopapad Added check

**Review by manopapad — APPROVED** [review]

**Comment by manopapad** [comment]
@trxcllnt how does this interact with https://github.com/nv-legate/legate.core/pull/411 ?

**Review by trxcllnt — APPROVED** [review]

**Review by trxcllnt — CHANGES_REQUESTED** [review]
I approved thinking this was a new PR, but I think this change was also made in #411. So maybe we can close this instead?

**Comment by manopapad** [comment]
I removed the changes that were covered by https://github.com/nv-legate/legate.core/pull/411, but kept the sanity check in `install.py`.

**Pull request merged**
