### PR TITLE
Mappers should skip collective views with no suitable instance

### PR DESCRIPTION
**Pull request by magnatelee**
This PR fixes an intermittent segfault in `legate_select_sources`.

### CODE REVIEW

**Comment by manopapad** [comment]
@lightsighter Shouldn't we expect the `find_instances_nearest_memory` API call to always return something (as long as a collective view has at least one thing in it)?

**Comment by lightsighter** [comment]
> Shouldn't we expect the find_instances_nearest_memory API call to always return something (as long as a collective view has at least one thing in it)?

@manopapad It should, if you have a counter example then I would like to see it.

**Comment by manopapad** [comment]
It sounds like @ipdemes is seeing such a case? @aschaffer was also seeing this happen while testing the quantile feature on 2 nodes.

**Comment by lightsighter** [comment]
I would like to examine at least one of those use cases to see what is happening.

**Comment by magnatelee** [comment]
I no longer see the issue that this PR meant to fix since I pulled the collective branch. I changed the code to assert collective sources being non-empty.

**Comment by ipdemes** [comment]
@magnatelee : should we close it then? I am planning to check if TorchSWE still sees the error with the most recent legion's collective branch as well

**Comment by magnatelee** [comment]
> @magnatelee : should we close it then? I am planning to check if TorchSWE still sees the error with the most recent legion's collective branch as well

I'm fine with closing it, but this PR would replace a segfault with a more informative assertion failure, so we could merge it for the sake of quality-of-life.

**Review by ipdemes — APPROVED** [review]

**Comment by ipdemes** [comment]
@magnatelee : this makes sense.

**Pull request merged**
