### PR TITLE
Draft: Update docs for canonical python

### PR DESCRIPTION
**Pull request by eddy16112**
This PR has to be merged after https://github.com/nv-legate/legate.core/pull/539

### CODE REVIEW

**Comment by bryevdv** [comment]
@eddy16112 can you take a look at https://github.com/nv-legate/cunumeric/pull/805 and see what if anything is missing? 

@manopapad @magnatelee is the plan to start publishing Sphinx docs for `legate` separately? If so I think perhaps most of the legate/python material from https://github.com/nv-legate/cunumeric/pull/805 could just be used there as well

**Comment by manopapad** [comment]
> @manopapad @magnatelee is the plan to start publishing Sphinx docs for legate separately? If so I think perhaps most of the legate/python material from https://github.com/nv-legate/cunumeric/pull/805 could just be used there as well

I think for the next release we want to spin up separate Sphinx docs for Legate Core, and move some of the material from the cuNumeric docs there (e.g. the instructions on invoking `legate`).

**Comment by magnatelee** [comment]
Yup, there'll be separate Sphinx+doxygen docs for Legate core. (See #563.)

**Comment by bryevdv** [comment]
@manopapad can this be closed (unmerged) ?

**Comment by manopapad** [comment]
Yes, all the information in this PR has made it to the mainline docs, closing this.

**Pull request closed without merging**
