### PR TITLE
fix several reference cycle / leak related bugs

### PR DESCRIPTION
**Pull request by rohany**
See individual commit comments for details.

### CODE REVIEW

**Comment by rohany** [comment]
cc @manopapad, turns out cycles we decided to ignore in the cycle checker that come from `__globals__` are actually important, see the first commit for details.

**Review by magnatelee — APPROVED** [review]

**Comment by manopapad** [comment]
@rohany Should/can we then remove the filtering of `__globals__` from the cycle detector here https://github.com/nv-legate/legate.core/blob/branch-22.12/legate/core/cycle_detector.py#L27?

**Comment by rohany** [comment]
I think so? I think those cycles should be "opt-in" to remove, rather than by default. When debugging this i was stuck for a while because the cycle detector didn't report that I had any cycles, so I spent time looking in the wrong places until i found that filtering in the cycle detector.

**Comment by manopapad** [comment]
Are you seeing any spurious cycles if you remove these lines from the filter? https://github.com/nv-legate/legate.core/blob/branch-22.12/legate/core/cycle_detector.py#L27-L29

I think we added this filter based on your feedback, that you were seeing a lot of spurious cycles.

**Comment by rohany** [comment]
I think that problem is that what we deemed as "spurious" is not actually spurious, as it was those cycles that lead to the leaks I debugged here. I only saw those cycles when I made that function return `False` always.

**Comment by manopapad** [comment]
Changed the filter on https://github.com/nv-legate/legate.core/pull/489

**Pull request merged**
